# Generated by Django 3.0.3 on 2020-03-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('note_text', models.CharField(max_length=120)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('last_up_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
